### ISSUE TITLE
 LowCardinality(Nullable(Date[32])) raise AttributeError: 'int' object has no attribute 'year'

### ISSUE THREAD

**Issue by jayvynl** [mymarilyn/clickhouse-driver#363] opened 2023-02-22 14:57 UTC
**Describe the bug**
 When inserting into LowCardinality(Nullable(Date)) or LowCardinality(Nullable(Date32)) raise AttributeError: 'int' object has no attribute 'year'

**To Reproduce**
```python
from clickhouse_driver import Client
from datetime import date

client = Client('localhost', settings={'allow_suspicious_low_cardinality_types': 1})
client.execute('create table test (lnd LowCardinality(Nullable(Date))) engine MergeTree order by ()')
client.execute('insert into test values', [{'lnd': date.today()}])

Traceback (most recent call last):
  File "/usr/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/wen/Projects/django-clickhouse-backend/venv/lib/python3.10/site-packages/clickhouse_driver/client.py", line 351, in execute
    rv = self.process_insert_query(
  File "/home/wen/Projects/django-clickhouse-backend/venv/lib/python3.10/site-packages/clickhouse_driver/client.py", line 578, in process_insert_query
    rv = self.send_data(sample_block, data,
  File "/home/wen/Projects/django-clickhouse-backend/venv/lib/python3.10/site-packages/clickhouse_driver/client.py", line 631, in send_data
    self.connection.send_data(block)
  File "/home/wen/Projects/django-clickhouse-backend/venv/lib/python3.10/site-packages/clickhouse_driver/connection.py", line 604, in send_data
    self.block_out.write(block)
  File "/home/wen/Projects/django-clickhouse-backend/venv/lib/python3.10/site-packages/clickhouse_driver/streams/native.py", line 38, in write
    write_column(self.context, col_name, col_type, items,
  File "/home/wen/Projects/django-clickhouse-backend/venv/lib/python3.10/site-packages/clickhouse_driver/columns/service.py", line 157, in write_column
    column.write_data(items, buf)
  File "/home/wen/Projects/django-clickhouse-backend/venv/lib/python3.10/site-packages/clickhouse_driver/columns/base.py", line 87, in write_data
    self._write_data(items, buf)
  File "/home/wen/Projects/django-clickhouse-backend/venv/lib/python3.10/site-packages/clickhouse_driver/columns/lowcardinalitycolumn.py", line 97, in _write_data
    self.nested_column.write_data(index, buf)
  File "/home/wen/Projects/django-clickhouse-backend/venv/lib/python3.10/site-packages/clickhouse_driver/columns/base.py", line 87, in write_data
    self._write_data(items, buf)
  File "/home/wen/Projects/django-clickhouse-backend/venv/lib/python3.10/site-packages/clickhouse_driver/columns/base.py", line 90, in _write_data
    prepared = self.prepare_items(items)
  File "/home/wen/Projects/django-clickhouse-backend/venv/lib/python3.10/site-packages/clickhouse_driver/columns/base.py", line 79, in prepare_items
    self.before_write_items(items, nulls_map=nulls_map)
  File "/home/wen/Projects/django-clickhouse-backend/venv/lib/python3.10/site-packages/clickhouse_driver/columns/datecolumn.py", line 38, in before_write_items
    item = date(item.year, item.month, item.day)
AttributeError: 'int' object has no attribute 'year'
```

**Expected behavior**
No exception.

**Versions**

- clickhouse-drive 0.2.5
- ClickHouse server 23.1.3.5
- Python 3.10

**Comment by jayvynl** [comment] 2023-02-22 15:01
The same bug also exists in UUIDField.

**Comment by Dmitry-k42** [comment] 2023-04-01 16:45
I run across the same issue. I wonder why the problem is still here. It seems to me, it's really uncommon to create low cardinality dates. Probably databases usually fill up every day and no one doesn't face the problem?
I made a fix for this, hope maintainers will accept my fix.

**Closed** 2023-04-01 22:32 UTC
