### ISSUE TITLE
Extremely slow on large select, http protocol almost 10 times faster

### ISSUE THREAD

**Issue by dmitriyshashkin** [mymarilyn/clickhouse-driver#32] opened 2018-03-20 12:34 UTC
It seems that selecting large datasets using the native client is extremely slow. Here is my benchmark https://gist.github.com/dmitriyshashkin/6a4849bdcf882ba340cdfbc1990da401

Initially, I've encountered this behavior on my own dataset, but I was able to reproduce it using the dataset and the structure described here https://clickhouse.yandex/docs/en/getting_started/example_datasets/ontime/

To simplify things a little bit I've used the data for just one month:  http://transtats.bts.gov/PREZIP/On_Time_On_Time_Performance_2017_12.zip

As you can see the fastest way to get the data is by using HTTP protocol with requests and pandas. The problem gets worse as the number of the rows grows, on my own dataset with 5M rows I waited for 1 hour before I had to interrupt the process. The bottleneck is not CH itself, the "top" command shows that all the work is done by python with 100% CPU utilization, while CH is almost idle.

**Comment by xzkostyan** [comment] 2018-03-21 09:08
Hi.

I haven't tried to play with provided data yet. But here is the explanation of speed loss.

HTTP client returns plain text (csv) that should be parsed for example with pandas. Native client returns Python types.

Pandas is complied library (correct me if I'm not right), this driver written in pure Python (except compression and hashing libraries). 

I'll try to cythonize some bottlenecks in source code. The main bottleneck is results trasposition from columnar to row-like form.

If your data processing is OK with columnar form your can specify `columnar=True` parameter in execute call. This will give significant speedup.

**Comment by xzkostyan** [comment] 2018-05-30 21:45
The problem is in very poor performance on String columns.

```python
In [1]: from clickhouse_driver import Client
   ...: 
   ...: client = Client('localhost')
   ...: %prun df = client.execute('select * from ontime LIMIT 40000')
   ...: 
```
```
         52078375 function calls in 28.330 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  4203004    8.476    0.000   16.829    0.000 socket.py:340(read)
  2723965    4.632    0.000    4.632    0.000 {method 'recv' of '_socket.socket' objects}
  1961317    1.918    0.000   22.761    0.000 reader.py:4(read_binary_str)
  1961406    1.338    0.000   10.071    0.000 reader.py:13(_read_one)
  1961381    1.184    0.000   11.255    0.000 reader.py:21(read_varint)
  2241317    1.170    0.000    2.925    0.000 {method 'decode' of 'str' objects}
  2240280    1.167    0.000   26.667    0.000 base.py:190(<genexpr>)
  2241317    0.899    0.000    1.754    0.000 utf_8.py:15(decode)
  2241317    0.855    0.000    0.855    0.000 {_codecs.utf_8_decode}
  5682043    0.851    0.000    0.851    0.000 {method 'seek' of 'cStringIO.StringO' objects}
  4203006    0.789    0.000    0.789    0.000 {cStringIO.StringIO}
        5    0.775    0.155    0.819    0.164 block.py:88(get_rows)
  1960000    0.747    0.000   23.484    0.000 stringcolumn.py:15(read)
```

```python
In [1]: from clickhouse_driver import Client
    ...: 
    ...: client = Client('localhost')
    ...: %prun df = client.execute('select Year, Quarter, Month, DayofMonth, DayOfWeek, AirlineID, OriginAirportID, OriginAirportSeqID, OriginCityMarketID, OriginWac, DestAirpo
    ...: rtID, DestAirportSeqID, DestCityMarketID, DestWac, CRSDepTime, DepTime, DepDelay, DepDelayMinutes, DepDel15, TaxiOut, WheelsOff, WheelsOn, TaxiIn, CRSArrTime, ArrTime,
    ...:  ArrDelay, ArrDelayMinutes, ArrDel15, ArrivalDelayGroups, Cancelled, Diverted, CRSElapsedTime, ActualElapsedTime, AirTime, Flights, Distance, DistanceGroup, CarrierDel
    ...: ay, WeatherDelay, NASDelay, SecurityDelay, LateAircraftDelay, Div1AirportID, Div1AirportSeqID, Div2AirportID, Div2AirportSeqID, Div3AirportID, Div3AirportSeqID, Div4Ai
    ...: rportID, Div4AirportSeqID, Div5AirportID, Div5AirportSeqID from ontime LIMIT 40000')
```

```
         21451 function calls in 0.625 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        5    0.289    0.058    0.300    0.060 block.py:88(get_rows)
        1    0.250    0.250    0.625    0.625 <string>:1(<module>)
      276    0.021    0.000    0.021    0.000 {method 'unpack' of 'Struct' objects}
     1612    0.017    0.000    0.017    0.000 {method 'recv' of '_socket.socket' objects}
      277    0.011    0.000    0.011    0.000 {range}
        8    0.008    0.001    0.309    0.039 client.py:111(store_query_result)
        1    0.006    0.006    0.373    0.373 client.py:100(receive_no_progress_result)
      260    0.005    0.000    0.005    0.000 base.py:130(make_struct)
     1619    0.004    0.000    0.023    0.000 socket.py:340(read)
        5    0.001    0.000    0.001    0.000 {method 'extend' of 'list' objects}
        7    0.001    0.000    0.049    0.007 native.py:58(read)
      633    0.001    0.000    0.014    0.000 reader.py:4(read_binary_str)
      710    0.001    0.000    0.015    0.000 reader.py:13(_read_one)
      260    0.001    0.000    0.002    0.000 service.py:35(get_column_by_spec)
      689    0.001    0.000    0.016    0.000 reader.py:21(read_varint)
      260    0.001    0.000    0.031    0.000 base.py:141(read_items)
     1621    0.001    0.000    0.001    0.000 {cStringIO.StringIO}
      633    0.001    0.000    0.001    0.000 {method 'decode' of 'str' objects}
      633    0.001    0.000    0.001    0.000 {_codecs.utf_8_decode}
```

**Comment by xzkostyan** [comment] 2018-09-18 19:04
Hi all!

After few optimization attempts I've come with following conclusions:

* Reading should be buffered on python-side and use massive buffer. Much more than socket's.
* Function calls should be inline in most heavy parts.
* String encoding/decoding should be optional. See `strings_as_bytes` flag in `settings={'strings_as_bytes': True}`. It's temporary name of the flag. With this flag set no decoding/encoding will be performed.

Results after optimization.

With decoding 

```python
In [1]: from clickhouse_driver import Client
   ...: 
   ...: client = Client('localhost')
   ...: %prun df = client.execute('select * from ontime LIMIT 40000')
```


```
         8502035 function calls in 5.352 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      245    1.401    0.006    4.122    0.017 stringcolumn.py:32(read_items)
  1961377    0.872    0.000    1.480    0.000 reader.py:22(read_varint)
  1961633    0.705    0.000    0.710    0.000 reader.py:97(read)
  2241317    0.652    0.000    0.652    0.000 {_codecs.utf_8_decode}
        5    0.646    0.129    0.666    0.133 block.py:88(get_rows)
  1961398    0.582    0.000    0.609    0.000 reader.py:122(read_one)
       35    0.179    0.005    0.321    0.009 stringcolumn.py:84(read_items)
        1    0.069    0.069    5.352    5.352 <string>:1(<module>)
   280000    0.056    0.000    0.056    0.000 {method 'rstrip' of 'unicode' objects}
       16    0.031    0.002    0.031    0.002 {method 'recv_into' of '_socket.socket' objects}
    40000    0.028    0.000    0.028    0.000 datecolumn.py:16(after_read_item)
      562    0.020    0.000    0.020    0.000 {range}
        1    0.018    0.018    5.280    5.280 result.py:38(get_result)
      545    0.016    0.000    4.526    0.008 base.py:96(_read_data)
        9    0.015    0.002    0.683    0.076 result.py:17(store)
      281    0.015    0.000    0.015    0.000 {method 'unpack' of 'Struct' objects}
    40005    0.011    0.000    0.039    0.000 base.py:115(<genexpr>)
      265    0.008    0.000    0.008    0.000 base.py:130(make_struct)
      545    0.005    0.000    4.531    0.008 base.py:88(read_data)
        7    0.003    0.000    4.553    0.650 native.py:59(read)
      545    0.002    0.000    0.007    0.000 service.py:35(get_column_by_spec)
     1317    0.002    0.000    0.004    0.000 {method 'decode' of 'bytearray' objects}
```

Without decoding

```python
In [1]: from clickhouse_driver import Client
   ...: 
   ...: client = Client('localhost', settings={'strings_as_bytes': True})
   ...: %prun df = client.execute('select * from ontime LIMIT 40000')
```

```
         5982038 function calls in 4.214 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      245    0.872    0.004    2.970    0.012 stringcolumn.py:66(read_items)
        5    0.836    0.167    0.859    0.172 block.py:88(get_rows)
  1961377    0.814    0.000    1.395    0.000 reader.py:22(read_varint)
  1961633    0.731    0.000    0.736    0.000 reader.py:97(read)
  1961398    0.557    0.000    0.581    0.000 reader.py:122(read_one)
       35    0.079    0.002    0.080    0.002 stringcolumn.py:123(read_items)
        1    0.075    0.075    4.214    4.214 <string>:1(<module>)
    40000    0.041    0.000    0.041    0.000 datecolumn.py:16(after_read_item)
        9    0.035    0.004    0.896    0.100 result.py:17(store)
        1    0.030    0.030    4.138    4.138 result.py:38(get_result)
       17    0.029    0.002    0.029    0.002 {method 'recv_into' of '_socket.socket' objects}
      562    0.023    0.000    0.023    0.000 {range}
      281    0.022    0.000    0.022    0.000 {method 'unpack' of 'Struct' objects}
      545    0.020    0.000    3.160    0.006 base.py:96(_read_data)
    40005    0.013    0.000    0.054    0.000 base.py:115(<genexpr>)
      265    0.008    0.000    0.008    0.000 base.py:130(make_struct)
      545    0.005    0.000    3.165    0.006 base.py:88(read_data)
        7    0.003    0.000    3.188    0.455 native.py:59(read)
      545    0.002    0.000    0.007    0.000 service.py:35(get_column_by_spec)
     1317    0.002    0.000    0.002    0.000 {_codecs.utf_8_decode}
     1317    0.002    0.000    0.005    0.000 {method 'decode' of 'bytearray' objects}
        5    0.002    0.000    0.002    0.000 {method 'extend' of 'list' objects}
      280    0.002    0.000    0.003    0.000 stringcolumn.py:151(create_string_column)
     1317    0.001    0.000    0.008    0.000 reader.py:14(read_binary_str_fixed_len)
      545    0.001    0.000    3.173    0.006 service.py:65(read_column)
     1317    0.001    0.000    0.011    0.000 reader.py:4(read_binary_str)
```

Without profiler data from one month is read in 38 seconds on my machine.

I'll continue digging into String field optimization.

**Comment by healiseu** [comment] 2018-09-27 13:59
Hi, thank you @dmitriyshashkin for sharing your benchark results and thank you @xzkostyan for the efforts to trace the problem and optimize clickhouse-driver. I have run 6 out of 10 queries on the whole dataset (166.63 million rows, 166.63 MB).

```python
# Queries from Clickhouse web site at
# https://clickhouse.yandex/docs/en/getting_started/example_datasets/ontime/

# Compute monthly average number of flights from the year 2000 to 2008
q0 = 'select avg(c1) from (select Year, Month, count(*) as c1 from ontime group by Year, Month);'

# The number of flights per day from the year 2000 to 2008
q1 = 'SELECT DayOfWeek, count(*) AS c FROM ontime WHERE Year >= 2000 AND Year <= 2008 GROUP BY DayOfWeek ORDER BY c DESC;'

# The number of flights delayed by more than 10 minutes, grouped by the day of the week, for 2000-2008
q2 = 'SELECT DayOfWeek, count(*) AS c FROM ontime WHERE DepDelay>10 AND Year >= 2000 AND Year <= 2008 GROUP BY DayOfWeek ORDER BY c DESC'

# The number of delays by airport for 2000-2008
q3 = 'SELECT Origin, count(*) AS c FROM ontime WHERE DepDelay>10 AND Year >= 2000 AND Year <= 2008 GROUP BY Origin ORDER BY c DESC LIMIT 10'

# The number of delays by carrier for 2007
q4 = 'SELECT Carrier, count(*) FROM ontime WHERE DepDelay>10  AND Year = 2007 GROUP BY Carrier ORDER BY count(*) DESC'

# The percentage of delays by carrier for 2007
q5 = 'SELECT Carrier, avg(DepDelay > 10) * 1000 AS c3 FROM ontime WHERE Year = 2007 GROUP BY Carrier ORDER BY Carrier'

# The previous request for a broader range of years, 2000-2008
q6 = 'SELECT Carrier, avg(DepDelay > 10) * 1000 AS c3 FROM ontime WHERE Year >= 2000 AND Year <= 2008 GROUP BY Carrier ORDER BY Carrier'

# Percentage of flights delayed for more than 10 minutes, by year
q7 = 'SELECT Year, avg(DepDelay > 10) FROM ontime GROUP BY Year ORDER BY Year'

# The most popular destinations by the number of directly connected cities for various year ranges
q8 = 'SELECT DestCityName, uniqExact(OriginCityName) AS u FROM ontime WHERE Year >= 2000 and Year <= 2010 GROUP BY DestCityName ORDER BY u DESC LIMIT 10;'

# 
q9 = 'select Year, count(*) as c1 from ontime group by Year;'

q10 = """
select min(Year), max(Year), Carrier, count(*) as cnt,
       sum(ArrDelayMinutes>30) as flights_delayed,
       round(sum(ArrDelayMinutes>30)/count(*),2) as rate
FROM ontime
WHERE
       DayOfWeek not in (6,7) and OriginState not in ('AK', 'HI', 'PR', 'VI')
       and DestState not in ('AK', 'HI', 'PR', 'VI')
       and FlightDate < '2010-01-01'
GROUP by Carrier
HAVING cnt > 100000 and max(Year) > 1990
ORDER by rate DESC
LIMIT 1000;"""

q11 = 'SELECT avg(cnt) FROM (SELECT Year,Month,count(*) AS cnt FROM ontime WHERE DepDel15=1 GROUP BY Year,Month)'

q12 = 'select avg(c1) from (select Year,Month,count(*) as c1 from ontime group by Year,Month)'

q13 = 'SELECT DestCityName, uniqExact(OriginCityName) AS u FROM ontime GROUP BY DestCityName ORDER BY u DESC LIMIT 10;'

q14 = 'SELECT OriginCityName, DestCityName, count() AS c FROM ontime GROUP BY OriginCityName, DestCityName ORDER BY c DESC LIMIT 10;'

q15 = 'SELECT OriginCityName, count() AS c FROM ontime GROUP BY OriginCityName ORDER BY c DESC LIMIT 10;'
```

## My results
* OS Environment: Linux Ubuntu x64
* Processor: Intel(R) Core(TM) i3 CPU 540  @ 3.07GHz
* Memory 16 GB

### Clickhouse
```python
%timeit -r 10 client.execute(q0)
1.33 s ± 63.8 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)
%timeit -r 10 client.execute(q1)
370 ms ± 33.4 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)
%timeit -r 10 client.execute(q2)
578 ms ± 19.5 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)
%timeit -r 10 client.execute(q3)
891 ms ± 42.9 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)
%timeit -r 10 client.execute(q4)
161 ms ± 3.4 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)
%timeit -r 10 client.execute(q5)
162 ms ± 14.4 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)
```

### Python requests
```python
%timeit -r 10 requests.get(url, {'query': q0})
1.39 s ± 83 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)
%timeit -r 10 requests.get(url, {'query': q1})
413 ms ± 55.6 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)
%timeit -r 10 requests.get(url, {'query': q2})
621 ms ± 47.1 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)
%timeit -r 10 requests.get(url, {'query': q3})
895 ms ± 18.5 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)
%timeit -r 10 requests.get(url, {'query': q4})
181 ms ± 4.89 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)
%timeit -r 10 requests.get(url, {'query': q5})
200 ms ± 22.1 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)
```
Clickhouse driver is slightly better and performance on average is pretty good for a python client and Clickhouse running on a 10 years old PC

**Comment by xzkostyan** [comment] 2018-10-09 17:45
Hi.

After final optimizations I've get 28/23 seconds for with/without decoding string read from `ontime` within one month on my machine. 0.0.15 version result is 167 seconds for this dataset.

New version profiling info:

Without decoding

```python 
In [1]: from clickhouse_driver import Client
   ...: 
   ...: client = Client('localhost', settings={'strings_as_bytes': True})
   ...: %prun df = client.execute('select * from ontime LIMIT 40000')
```

```
         2342591 function calls in 2.022 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      245    0.919    0.004    1.117    0.005 bufferedreader.py:55(read_strings)
        5    0.575    0.115    0.593    0.119 block.py:88(get_rows)
  2240004    0.228    0.000    0.228    0.000 {method 'tobytes' of 'memoryview' objects}
       35    0.079    0.002    0.111    0.003 stringcolumn.py:97(read_items)
       16    0.034    0.002    0.034    0.002 {method 'recv_into' of '_socket.socket' objects}
    40000    0.026    0.000    0.026    0.000 datecolumn.py:16(after_read_item)
        1    0.022    0.022    2.022    2.022 <string>:1(<module>)
      562    0.018    0.000    0.018    0.000 {range}
        1    0.017    0.017    1.997    1.997 result.py:38(get_result)
      281    0.017    0.000    0.017    0.000 {method 'unpack' of 'Struct' objects}
        9    0.015    0.002    0.610    0.068 result.py:17(store)
      545    0.014    0.000    1.310    0.002 base.py:96(_read_data)
    40005    0.009    0.000    0.036    0.000 base.py:115(<genexpr>)
      265    0.008    0.000    0.008    0.000 base.py:130(make_struct)
      545    0.007    0.000    0.007    0.000 base.py:16(__init__)
      545    0.005    0.000    1.315    0.002 base.py:88(read_data)
     1634    0.003    0.000    0.008    0.000 bufferedreader.py:19(read)
     1318    0.003    0.000    0.011    0.000 reader.py:4(read_binary_str)
        7    0.002    0.000    1.342    0.192 native.py:59(read)
      545    0.002    0.000    0.011    0.000 service.py:36(get_column_by_spec)
     1318    0.001    0.000    0.004    0.000 {method 'decode' of 'bytearray' objects}
        5    0.001    0.000    0.001    0.000 {method 'extend' of 'list' objects}
     1379    0.001    0.000    0.030    0.000 reader.py:22(read_varint)
     1318    0.001    0.000    0.001    0.000 {_codecs.utf_8_decode}
      280    0.001    0.000    0.008    0.000 stringcolumn.py:126(create_string_column)
     1318    0.001    0.000    0.006    0.000 reader.py:14(read_binary_str_fixed_len)
      545    0.001    0.000    1.328    0.002 service.py:69(read_column)
     1400    0.001    0.000    0.029    0.000 bufferedreader.py:46(read_one)
     1318    0.001    0.000    0.002    0.000 utf_8.py:15(decode)
      265    0.001    0.000    0.032    0.000 base.py:141(read_items)
```

With decoding

```python 
In [1]: from clickhouse_driver import Client
   ...: 
   ...: client = Client('localhost', settings={'strings_as_bytes': False})
   ...: %prun df = client.execute('select * from ontime LIMIT 40000')
```

```
         4862611 function calls in 3.089 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      245    1.297    0.005    1.938    0.008 bufferedreader.py:55(read_strings)
        5    0.588    0.118    0.607    0.121 block.py:88(get_rows)
  2241318    0.516    0.000    0.516    0.000 {_codecs.utf_8_decode}
  2240004    0.228    0.000    0.228    0.000 {method 'tobytes' of 'memoryview' objects}
       35    0.182    0.005    0.316    0.009 stringcolumn.py:54(read_items)
        1    0.051    0.051    3.089    3.089 <string>:1(<module>)
       16    0.037    0.002    0.037    0.002 {method 'recv_into' of '_socket.socket' objects}
   280000    0.029    0.000    0.029    0.000 {method 'rstrip' of 'str' objects}
    40000    0.027    0.000    0.027    0.000 datecolumn.py:16(after_read_item)
      562    0.020    0.000    0.020    0.000 {range}
        1    0.017    0.017    3.035    3.035 result.py:38(get_result)
       10    0.015    0.002    0.624    0.062 result.py:17(store)
      281    0.015    0.000    0.015    0.000 {method 'unpack' of 'Struct' objects}
      545    0.014    0.000    2.333    0.004 base.py:96(_read_data)
    40005    0.010    0.000    0.037    0.000 base.py:115(<genexpr>)
      265    0.008    0.000    0.008    0.000 base.py:130(make_struct)
      545    0.007    0.000    0.007    0.000 base.py:16(__init__)
      545    0.004    0.000    2.338    0.004 base.py:88(read_data)
     1634    0.003    0.000    0.006    0.000 bufferedreader.py:19(read)
        7    0.002    0.000    2.361    0.337 native.py:59(read)
      545    0.002    0.000    0.012    0.000 service.py:36(get_column_by_spec)
        5    0.001    0.000    0.001    0.000 {method 'extend' of 'list' objects}
     1383    0.001    0.000    0.034    0.000 reader.py:22(read_varint)
     1318    0.001    0.000    0.003    0.000 {method 'decode' of 'bytearray' objects}
      280    0.001    0.000    0.008    0.000 stringcolumn.py:126(create_string_column)
     1318    0.001    0.000    0.009    0.000 reader.py:4(read_binary_str)
     1318    0.001    0.000    0.006    0.000 reader.py:14(read_binary_str_fixed_len)
```

I thing C extension is the second stage. Optimized code in master now and will be in upcoming 0.0.16 release.

**Comment by xzkostyan** [comment] 2019-07-17 18:34
Good news everyone. I'm playing with cython right now. Reading whole month (464205 rows) takes approximately 5 seconds.

**Comment by xzkostyan** [comment] 2019-08-08 07:49
You can try version 0.1.0. It contains String `SELECT` optimizations.

**Comment by xzkostyan** [comment] 2019-08-17 15:40
@dmitriyshashkin should we close this issue?

**Comment by xzkostyan** [comment] 2020-05-10 14:48
Performance section has been added to docs: https://clickhouse-driver.readthedocs.io/en/latest/performance.html

**Closed by xzkostyan** 2020-05-10 14:48 UTC
