### ISSUE TITLE
Geting NotImplementedError when i am doing query on array column

### ISSUE THREAD

**Issue by AbhishekOnedigital** [mymarilyn/clickhouse-driver#154] opened 2020-07-06 11:20 UTC
**Describe the bug**
 query 
``` 
client.execute("""select field1   as field1,count(*) as count  FROM table  where {some condition}
 GROUP BY field1)
```
here field1 is array 
error 
```
  File "/usr/lib/python3.6/site-packages/clickhouse_driver/client.py", line 165, in execute
    types_check=types_check, columnar=columnar
  File "/usr/lib/python3.6/site-packages/clickhouse_driver/client.py", line 205, in process_ordinary_query
    columnar=columnar)
  File "/usr/lib/python3.6/site-packages/clickhouse_driver/client.py", line 74, in receive_result
    self.receive_no_progress_result(result, columnar)
  File "/usr/lib/python3.6/site-packages/clickhouse_driver/client.py", line 101, in receive_no_progress_result
    packet = self.receive_packet()
  File "/usr/lib/python3.6/site-packages/clickhouse_driver/client.py", line 124, in receive_packet
    packet = self.connection.receive_packet()
  File "/usr/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 263, in receive_packet
    packet.block = self.receive_data()
  File "/usr/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 326, in receive_data
    block = self.block_in.read()
  File "/usr/lib/python3.6/site-packages/clickhouse_driver/streams/native.py", line 77, in read
    column = read_column(column_type, n_rows, self.fin)
  File "/usr/lib/python3.6/site-packages/clickhouse_driver/columns/service.py", line 56, in read_column
    return column.read_data(n_items, buf)
  File "/usr/lib/python3.6/site-packages/clickhouse_driver/columns/arraycolumn.py", line 61, in read_data
    return self._read(rows, buf)
  File "/usr/lib/python3.6/site-packages/clickhouse_driver/columns/arraycolumn.py", line 168, in _read
    nulls_map=nulls_map[prev_offset:prev_offset + size]
  File "/usr/lib/python3.6/site-packages/clickhouse_driver/columns/base.py", line 99, in _read_data
    items = self.read_items(n_items, buf)
  File "/usr/lib/python3.6/site-packages/clickhouse_driver/columns/base.py", line 120, in read_items
    raise NotImplementedError
NotImplementedError
```
- Python version. - 3.6

**Comment by xzkostyan** [comment] 2020-07-07 11:18
It's not possible to reproduce the problem with provided data.

Could you provide more specific DDL for table creation?
Which package version is affected?

**Comment by slowpilot** [comment] 2020-07-10 11:03
It really raising NotImplementedError on array column select. affected version is 0.1.4, 0.1.3 works fine

**Comment by xzkostyan** [comment] 2020-07-10 20:39
I still can't reproduce the issue.

```python
In [1]: from clickhouse_driver import Client                                  

In [2]: Client.from_url('clickhouse://localhost').execute('select range(10)') 
Out[2]: [([0, 1, 2, 3, 4, 5, 6, 7, 8, 9],)]

In [3]: from clickhouse_driver import __version__                             

In [4]: __version__                                                           
Out[4]: '0.1.4'
```

All [array tests](https://github.com/mymarilyn/clickhouse-driver/blob/master/tests/columns/test_array.py) are also green.

**Comment by Hungsiro506** [comment] 2020-07-29 09:06
I got the same bug when try to query from table have Array(Array(String)) column with empty data. 
Its okey to query empty Array(String) column but its not okey to query empty Array(Array(String). 
The bug can be reproduced by the following code :
Change the uri to your clickhouse server.

``` python
uri = 'clickhouse-uri '  
engine = create_engine(uri)
session = make_session(engine)
metadata = MetaData(bind=engine)
client = Client.from_url(uri)

Base = get_declarative_base(metadata=metadata)


class NestedArrayArray(Base):
    __tablename__ = 'nested_array_array_test'
    anonymous_id = Column(types.String, primary_key=True)
    arr_keys = Column('arr_prop.keys', types.Array(types.String))
    arr_vals = Column('arr_prop.vals', types.Array(types.Array(types.String)))
    __table_args__ = (
        engines.Memory(),
    )


def create_example_data():
    table = NestedArrayArray.__table__
    table.create()
    data = [
        {
            'anonymous_id': 'brian-1',
            'arr_prop.keys': ['ab', 'c'], 'arr_prop.vals': [['a', 'b'], ['c']]
        },
        {
            'anonymous_id': 'brian-3',
            'arr_prop.keys': [], 'arr_prop.vals': []
        },
        {
            'anonymous_id': 'brian-2',
            'arr_prop.keys': ['empty'], 'arr_prop.vals': [[]]
        },
    ]
    # Emits single INSERT statement.
    session.execute(table.insert(), data)


def query():
    query_1 = "select * from nested_array_array_test where  anonymous_id = 'brian-1' "
    query_2 = "select * from nested_array_array_test where  anonymous_id = 'brian-2' "
    query_3 = "select * from nested_array_array_test where  anonymous_id = 'brian-3' "
    result1 = client.execute(query_1)
    print(result1)
    result2 = client.execute(query_2)
    print(result2)
    result3 = client.execute(query_3)
    print(result3)


if __name__ == "__main__":
    from clickhouse_driver import __version__
    print(__version__)
   create_example_data()
   query()
```

**Comment by xzkostyan** [comment] 2020-08-14 08:43
Fixed in https://github.com/mymarilyn/clickhouse-driver/pull/161

**Closed** 2020-09-20 22:16 UTC
